apiVersion: apps/v1
kind: Deployment
metadata:
  name: testt
  labels:
    app: testt
  namespace: tqs-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testt
  template:
    metadata:
      labels:
        app: testt
    spec:
      containers:
        - name: testt
          image: acrworkflow1687825403901.azurecr.io/image-workflow-1687825403901:latest
          ports:
            - containerPort: 80