apiVersion: apps/v1
kind: Deployment
metadata:
  name: tqs-backend
  namespace: tqs-services
  labels:
    run: tqs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tqs-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tqs-backend
    spec:
      containers:
        - name: tqs-backend
          image: tqscontainer2.azurecr.io/grupo3/tqs-backend:1.23.0-SNAPSHOT
          imagePullPolicy: Always
          volumeMounts:
            - name: log
              mountPath: /var/log
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              value: "jdbc:mysql://mysql-service:3306/pickuppoint"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: MysqlPassword12345
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 1Gi
      volumes:
        - name: log
          emptyDir: {}
