apiVersion: apps/v1
kind: Deployment
metadata:
  name: Backend-DevOps
  labels:
    app: Backend-DevOps
  namespace: tqs-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Backend-DevOps
  template:
    metadata:
      labels:
        app: Backend-DevOps
    spec:
      containers:
        - name: Backend-DevOps
          image: tqscontainer2.azurecr.io/tqs-backendd:latest
          ports:
            - containerPort: 80