apiVersion: v1
kind: Service
metadata:
  name: Backend-DevOps
  namespace: tqs-services
spec:
  type: LoadBalancer
  selector:
    app: Backend-DevOps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80