on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      env:
        required: false
        type: string
        default: 'dev'
      working-directory:
        required: false
        type: string
        default: '.'
      java-version:
        required: false
        type: string
        default: '17'
      maven-params:
        required: false
        type: string
        default: ''
jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.env || 'dev' }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ inputs.java-version }}
          cache: maven
      - name: Set Maven Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Build
        run: mvn clean install -DskipTests ${{ inputs.maven-params }} --file pom.xml
      - name: Login into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Get Commit Short SHA
        run: echo "SHORT_SHA=`git rev-parse --short "${{ github.sha }}"`" >> $GITHUB_ENV
      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/synergy/${{ inputs.image-name }}:${{ env.SHORT_SHA }}