name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Build and deploy
        run: |
          cd PickupPointBackEnd
          mvn clean package

          # Example: Deploy to a remote Ubuntu machine via SSH
          # Make sure to replace the placeholders with your actual values
          ssh fantao@deti-tqs-08 "mkdir -p /project"
          scp target/PickupPointBackEnd-0.0.1-SNAPSHOT.jar fantao@deti-tqs-08:/project
          ssh fantao@deti-tqs-08 "sudo systemctl restart PickupPointBackEnd-0.0.1-SNAPSHOT"
