name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: TQSProject
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd PickupPointBackEnd
          mvn clean package


  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.AZURE_WEBAPP_NAME }}"
          publish-profile: "${{ secrets.AZURE_PUBLISH_PROFILE }}"
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
      
