name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: pickuppoint
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Maven
      run: |
          cd PickupPointBackEnd
          mvn clean install
    - name: Build and Analyze
      env:
        SONAR_TOKEN: sqp_7f9a0c026c5a6a2a3d45f59271d8904eddbbe26e
      run: |
        cd PickupPointBackEnd
        mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TQS_Backend

